# Exercise 1 

In this exercise, we will go over an object-oriented programming exercises related to standard operations with `pandas` data frames. 

### Exercise 1(a) (10 points)

Create a class called `DataFrameProcessor` that will handle basic operations on a pandas DataFrame. Your class should:

1. Initialize with a pandas DataFrame.
2. Have a method get_column_stats(column_name) that returns the mean, median, and standard deviation of the specified column.
3. Have a method filter_rows(column_name, threshold) that returns a new DataFrame with rows where the values in the specified column are greater than the given threshold.
4. Have a method add_new_column(column_name, data) that adds a new column with the specified name and data to the DataFrame.

In [1]:
import pandas as pd
import numpy as np

class DataFrameProcessor:
    def __init__(self, df):
        self.df = df

    def get_column_stats(self, column_name):
        return {
            "mean": self.df[column_name].mean(),
            "median": self.df[column_name].median(),
            "std": self.df[column_name].std()
        }

    def filter_rows(self, column_name, threshold):
        return self.df[self.df[column_name] > threshold]

    def add_new_column(self, column_name, data):
        self.df[column_name] = data
        return self.df

### Exercise 1(b) (3 points)

Create a data frame called `df` with three columns and 20 rows. Fill the data frame with random integers from 1 to 20. Hint: use `np.random.randint` from `numpy` to generate the random integers.

In [2]:
df = pd.DataFrame(
    np.random.randint(1, 21, size=(20, 3)),
    columns=["col_1", "col_2", "col_3"]
)

df

    col_1  col_2  col_3
0       4      1     15
1       2      7     16
2       2     17     19
3      10      3     13
4      14     10     17
5      15      7      5
6       3      3      5
7       1     12      5
8      18     20     15
9      14     10     17
10     16      6      5
11      3     18     20
12      9      3     19
13     12      8     19
14      8     10      5
15      7     16     15
16      9      2      1
17     12     20      2
18      9     17     12
19      1      6     11

### Exercise 1(c) (4 points)

Using the `DataFrameProcessor` class, report the stats for each of the columns in `df`.

In [3]:
processor = DataFrameProcessor(df)

print("col_1:", processor.get_column_stats("col_1"))
print("col_2:", processor.get_column_stats("col_2"))
print("col_3:", processor.get_column_stats("col_3"))

col_1: {'mean': np.float64(8.45), 'median': np.float64(9.0), 'std': np.float64(5.4141627140987225)}
col_2: {'mean': np.float64(9.8), 'median': np.float64(9.0), 'std': np.float64(6.271069748414036)}
col_3: {'mean': np.float64(11.8), 'median': np.float64(14.0), 'std': np.float64(6.370986868940363)}

### Exercise 1(d) (3 points)

Filter the rows where `col_3` is greater than 12.

In [4]:
filtered_df = processor.filter_rows("col_3", 12)

filtered_df

    col_1  col_2  col_3
0       4      1     15
1       2      7     16
2       2     17     19
3      10      3     13
4      14     10     17
8      18     20     15
9      14     10     17
11      3     18     20
12      9      3     19
13     12      8     19
15      7     16     15

### Exercise 1(e) (3 points)

Create a list with random intergers from 1 to 20. Add the list to `df` as new column called `col_4`.

In [5]:
new_data = np.random.randint(1, 21, size=20)

processor.add_new_column("col_4", new_data)

    col_1  col_2  col_3  col_4
0       4      1     15     19
1       2      7     16      2
2       2     17     19     19
3      10      3     13     15
4      14     10     17     17
5      15      7      5      5
6       3      3      5     17
7       1     12      5      8
8      18     20     15     13
9      14     10     17      7
10     16      6      5      2
11      3     18     20     16
12      9      3     19     12
13     12      8     19      5
14      8     10      5     16
15      7     16     15     18
16      9      2      1      7
17     12     20      2     16
18      9     17     12     16
19      1      6     11     19

# Exercise 2 (10 points)

Data pre-processing with OOP. Create a Python class called `DataPreprocessor` that:

1. Takes a pandas DataFrame as input.
2. Provides methods to:
   - Handle missing values by filling them with the column mean.
   - Normalize numerical columns between 0 and 1.
3. Returns the cleaned DataFrame when called with `.transform()`

Consider `df` as DataFrame to test the class.

```
data = {
    "age": [25, np.nan, 35, 40, np.nan],
    "income": [50000, 60000, np.nan, 80000, 75000],
    "gender": ["M", "F", "M", "F", "M"]
}
df = pd.DataFrame(data)
```

In [6]:
data = {
    "age": [25, np.nan, 35, 40, np.nan],
    "income": [50000, 60000, np.nan, 80000, 75000],
    "gender": ["M", "F", "M", "F", "M"]
}

df = pd.DataFrame(data)


class DataPreprocessor:
    def __init__(self, df):
        self.df = df.copy()

    def handle_missing_values(self):
        numeric_columns = self.df.select_dtypes(include=np.number).columns

        for column in numeric_columns:
            self.df[column] = self.df[column].fillna(
                self.df[column].mean()
            )

    def normalize(self):
        numeric_columns = self.df.select_dtypes(include=np.number).columns

        for column in numeric_columns:
            minimum = self.df[column].min()
            maximum = self.df[column].max()

            self.df[column] = (
                (self.df[column] - minimum) /
                (maximum - minimum)
            )

    def transform(self):
        self.handle_missing_values()
        self.normalize()
        return self.df


processor = DataPreprocessor(df)
cleaned_df = processor.transform()

cleaned_df

        age    income gender
0  0.000000  0.000000      M
1  0.555556  0.333333      F
2  0.666667  0.541667      M
3  1.000000  1.000000      F
4  0.555556  0.833333      M

# Exercise 3 

In this exercise, we will practice `merge` with `pandas` data frames. Merging in `pandas` is a way of combining two data frames based on a common column or set of columns. Think of it like putting together pieces of a puzzle where both tables have a shared piece of information (like a key or ID number) that helps you connect the rows that belong together.

### Exercise 3(a) (2 points)

Load the `pandas` library.

In [7]:
import pandas as pd

### Exercise 3(b) (4 points)

Create three `pandas` data-frames based on the following raw data:

```
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
```

Call them `dat_1`, `dat_2`, and `dat_3`, respectively.

In [8]:
raw_data_1 = {
    'subject_id': ['1', '2', '3', '4', '5'],
    'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
    'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']
}

raw_data_2 = {
    'subject_id': ['4', '5', '6', '7', '8'],
    'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
    'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']
}

raw_data_3 = {
    'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
    'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]
}

dat_1 = pd.DataFrame(raw_data_1)
dat_2 = pd.DataFrame(raw_data_2)
dat_3 = pd.DataFrame(raw_data_3)

### Exercise 3(c) (3 points)

Combine `dat_1` and `dat_2` along the rows and call the resulting data frame `all_data`.

In [9]:
all_data = pd.concat([dat_1, dat_2], axis=0)

all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

### Exercise 3(d) (3 points)

Combine `dat_1` and `dat_2` along the columns and call the resulting data frame `all_data_col`.

In [10]:
all_data_col = pd.concat([dat_1, dat_2], axis=1)

all_data_col

  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5     Ayoung   Atiches          8      Betty    Btisan

### Exercise 3(e) (3 points)

Merge `all_data` and `dat_3` using `subject_id` as the key variable, and call the resulting data frame `dat_merge`.

In [11]:
dat_merge = pd.merge(all_data, dat_3, on="subject_id")

dat_merge

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          5     Ayoung   Atiches       16
5          4      Billy    Bonder       61
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

### Exercise 3(f) (3 points)

Merge `dat_1` and `dat_2` using `subject_id` as the key variable, and call the resulting data frame `dat_merge_1`.

In [12]:
dat_merge_1 = pd.merge(dat_1, dat_2, on="subject_id")

dat_merge_1

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Exercise 3(g) (3 points)

Merge all the values in `dat_1` and `dat_2`, using `subject_id` as the key variable, with matching records from the left data frame. Call the resulting data frame `dat_merge_2`.

In [13]:
dat_merge_2 = pd.merge(
    dat_1,
    dat_2,
    on="subject_id",
    how="left"
)

dat_merge_2

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black

# Exercise 4

In this exercise, we will practice functional programming with `pandas` data frame. Functional programming concepts with `pandas` involves using `apply()`, `map()`, and `lambda()` functions. 

### Exercise 4(a) (3 points)

Imagine you are working with a data set of customers that includes their purchase amounts in different categories. The goal is to apply transformations and extract insights using functional programming techniques. Create the below `pandas` data frame.

```
import pandas as pd

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Groceries': [120, 150, 80, 90, 130],
    'Electronics': [200, 0, 100, 300, 150],
    'Clothing': [50, 60, 45, 70, 30]
}

df = pd.DataFrame(data)
```

### Exercise 4(b) (3 points)

Use the `apply()` function to calculate the total spending for each customer (sum of `Groceries`, `Electronics`, and `Clothing`).

### Exercise 4(c) (3 points)

Use a `lambda` function to classify customers as `High`, `Medium`, or `Low` spenders based on their total spending:

- High: Total spending >= 400
- Medium: Total spending between 200 and 399
- Low: Total spending < 200

### Exercise 4(d) (3 points)

Calculate the percentage of spending in `Electronics` compared to the `Total_Spend` for each customer.

### Exercise 4(e) (4 points)

Write a custom function that can be passed to `apply()` to give a 10% discount on electronics spending if a customer's total spend is above $400.